version: '3.8'
services:
  dotnet_postgres:
    image: postgres:alpine
    container_name: dotnet_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: myDB
    
  dotnet_rabbitmq:
    image: rabbitmq:3-alpine
    container_name: dotnet_rabbitmq
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    
  dotnet_minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpassword
    
#
#  dotnet_mongodb:
#    image: mongo:latest
#
#  dotnet_jaeger:
#    image: jaegertracing/all-in-one:latest
  
  dotnet_main:
    image: homework.main
    container_name: Homework.MainProject
    ports:
      - "8080:80"
    build:
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    environment:
      ConnectionStrings__Default: "User ID=root;Password=myPassword;Host=dotnet_postgres;Port=5432;Database=myDB;Pooling=true;Connection Lifetime=0;"
      RabbitMqConfig__Username: "admin"
      RabbitMqConfig__Password: "admin"
      RabbitMqConfig__Hostname: "dotnet_rabbitmq"
      RabbitMqConfig__Port: 5672
    depends_on:
      - dotnet_postgres
      - dotnet_rabbitmq
  
  dotnet_mailing:
    image: homeworks.mailing.api
    container_name: Homeworks.Mailing.API
    ports:
      - "8081:80"
    build:
      dockerfile: Dotnet.Homeworks.Mailing.API/Dockerfile
    environment:
      EmailConfig__Email: "oristask@gmail.com"
      EmailConfig__Password: "gomlmldthveiefjr"
      EmailConfig__Host: "smtp.gmail.com"
      EmailConfig__Port: 25
      EmailConfig__WithSsl: true
      RabbitMqConfig__Username: "admin"
      RabbitMqConfig__Password: "admin"
      RabbitMqConfig__Hostname: "dotnet_rabbitmq"
      RabbitMqConfig__Port: 5672
    depends_on: 
      - dotnet_rabbitmq

  dotnet_storage:
    image: homeworks.storage.api
    container_name: Homeworks.Storage.API
    ports:
      - "8082:80"
    build:
      dockerfile: Dotnet.Homeworks.Storage.API/Dockerfile
    environment:
      MinioConfig__Username: admin
      MinioConfig__Password: adminpassword
      MinioConfig__Endpoint: minio
      MinioConfig__Port: 9000
      MinioConfig__WithSsl: false
    depends_on: 
      - dotnet_minio
